source 'https://rubygems.org'
ruby '2.7.1'
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'
gem 'railties', '6.0.2.2'
gem 'sprockets', '~> 4'
gem 'sprockets-rails', '3.2.1'
gem 'xlsx_writer', '0.4.4'
gem 'mysql2', '0.5.1'
# gem 'activerecord-mysql2-adapter'
gem 'devise'
gem 'devise-encryptable', '0.2.0'
gem 'slim-rails', '3.1.0'
gem 'twitter-bootstrap-rails', '~> 2.1.9'
gem 'rails-settings-cached', '0.6.6'
gem 'rake', '< 11.0'
gem 'responders'

gem 'sass-rails', '>= 6'
gem 'yajl-ruby', '~>1.3.1'
gem 'coffee-rails', '5.0.0'
gem 'therubyracer', '0.12.3', :platforms => :ruby
gem 'uglifier', '3.0.0'
gem 'sassc', '2.4.0'
gem 'active_link_to', '1.0.3'
gem 'jquery-rails'
gem 'nested_form', '0.3.2'
gem 'kaminari', '0.17.0'
gem 'acts_as_archival', '1.1.1'
gem 'paranoia', '2.4.2'
gem 'daemons', '1.2.3'
gem 'hashie_rails', '0.0.4'
group :development do
  gem 'better_errors', '2.1.1'
  gem "binding_of_caller", ">= 0.6.9"
  gem 'pry', '0.10.3'
  gem 'pry-nav', '0.2.4'
  gem 'rspec-rails', '~> 3.1.0'
  gem 'awesome_print', '1.7.0'
  # gem 'quiet_assets'
  gem 'copyright-header', '1.0.15'
  gem 'capistrano', '3.10.2'
  gem 'capistrano-rails', '1.1.3'
  gem "letter_opener", '1.4.1'
  gem 'listen'
end
gem 'capistrano-rvm', '0.1.2'
gem 'browser'
gem 'gon', '6.3.1'
gem 'rest-client', '1.8.0'
gem 'slim', '3.0.7'
gem 'paypal-sdk-rest', '1.4.6'
gem 'activemerchant'
gem 'paper_trail', '10.3.1'
gem 'carrierwave', '0.11.2'
gem 'rmagick', '2.15.4'
gem 'tinymce-rails', '4.3.13'
gem 'wicked_pdf', '~> 2.0.1'
gem 'wkhtmltopdf-binary', '~> 0.9.9.3'
gem 'fullcalendar-rails', '2.0.2.0'
gem 'momentjs-rails', '2.11.1'
# testing
gem 'factory_girl_rails', '~> 4.5.0'
gem 'factory_girl', '~> 4.5.0'
gem 'faker', '~> 1.4.3'
gem 'activerecord-session_store'
gem 'stripe', '1.56.0'
gem 'figaro', '1.1.1'

group :test do
  gem 'shoulda-matchers', '2.8.0'
  gem 'shoulda', '~> 3.5.0'
  gem 'rspec-its', '1.2.0'
end

gem 'money', '~>  6.5.0'
gem 'osb_api', path: 'vendor/engines/osb_api'

# To use Jbuilder templates for JSON
gem 'jbuilder', '~> 2.0'
gem 'oauth', '0.4.7'
gem 'oauth2', '1.4.3'
gem 'roxml'
gem 'nokogiri'
gem 'quickbooks-ruby'
gem 'qbo_api'
gem 'ruby-freshbooks', '0.4.1'
gem 'rolify', '5.1.0'
gem 'puma', '3.11.0'


gem 'elasticsearch-model', '5.0.0'
gem 'elasticsearch-rails', '5.0.0'

gem 'exception_notification-rake', '0.3.1'

gem 'whenever', '0.9.7'
gem 'browser-timezone-rails'
gem 'js_cookie_rails', '1.0.1'
gem 'i18n-js', '~> 3.0', '>= 3.0.5'
gem 'simple_form', '5.0.0'
gem 'cocoon', '~> 1.2', '>= 1.2.11'
# gem 'nouislider-rails', '~> 8.2', '>= 8.2.1'
gem 'simple_token_authentication', '~> 1.0'
gem 'sidekiq', '>= 5.2.7'
gem 'sidekiq-symbols', '0.2.0'
gem "pundit"
gem 'groupdate'
gem 'chartkick'
gem "hashid-rails", "~> 1.0"
gem 'public_activity', "~> 1.6.4"
gem 'to_words'
gem 'trackstamps'
gem 'jquery-infinite-pages'
gem "introjs-rails"
gem 'jquery-validation-rails'
gem 'bigdecimal', '~> 1.2', '>= 1.2.7'
gem 'actionpack', '6.0.2.2  '
gem 'activesupport', '~> 6.0.2.2'
gem 'activemodel', '~> 6.0.2.2'
gem 'activerecord', '~> 6.0.2.2'
gem "webpacker"
gem 'hammerjs-rails'
gem 'faraday', '1.0.1'
gem 'rack-cors', '~> 1.1', '>= 1.1.1'