source 'https://rubygems.org'
ruby '2.3.2'
gem 'rails', '~> 4.2.5'

gem 'bundler'
gem 'railties'
gem 'responders', '~> 2.0'
gem 'web-console', '~> 2.0'
gem 'sprockets', '~> 2.12.3'
gem 'sprockets-rails', '~> 2.2.2'
gem 'xlsx_writer', '0.4.4'
gem 'mysql2', '0.3.20'
gem 'devise'
gem 'devise-encryptable'
gem 'slim-rails', '3.1.0'
gem 'twitter-bootstrap-rails', '~> 2.1.9'
gem 'rails-settings-cached', '0.4.1'
gem 'money', '~>  6.5.0'
gem 'dj_mon', git: 'https://github.com/akshayrawat/dj_mon'
gem 'osb_api', path: 'vendor/engines/osb_api'
gem 'jbuilder', '~> 2.0'
gem 'oauth', '0.4.7'
gem 'roxml', '3.3.1'
gem 'nokogiri', '1.6.8'
gem 'quickbooks-ruby', '0.4.4'
gem 'active_link_to', '1.0.3'
gem 'jquery-rails', '~> 2.1.4'
gem 'nested_form', '0.3.2'
gem 'kaminari', '0.17.0'
gem 'acts_as_archival', '1.1.1'
gem 'paranoia', '2.1.5'
gem 'activerecord-mysql-adapter', '0.0.1'
gem 'delayed_job_active_record'
gem 'daemons', '1.2.3'
gem 'hashie-forbidden_attributes'
gem 'browser', '2.1.0'
gem 'gon', '6.0.1'
gem 'rest-client', '1.8.0'
gem 'slim', '3.0.7'
gem 'paypal-sdk-rest', '1.4.6'
gem 'activemerchant', '1.60.0'
gem 'paper_trail', '5.1.1'
gem 'carrierwave', '0.11.2'
gem 'rmagick', '2.15.4'
gem 'tinymce-rails', '4.3.13'
gem 'wicked_pdf', '~> 1.0.6'
gem 'wkhtmltopdf-binary', '~> 0.12.3.1'
gem 'fullcalendar-rails', '2.0.2.0'
gem 'momentjs-rails', '2.11.1'
gem 'activerecord-session_store', '1.0.0'
gem 'ruby-freshbooks', '0.4.1'
gem 'cancancan', '1.15.0'
gem 'rolify', '5.1.0'

group :assets do
  gem 'sass-rails', '5.0.4'
  gem 'coffee-rails', '4.1.1'
  gem 'therubyracer', '0.12.2', :platforms => :ruby
  gem 'uglifier', '3.0.0'
  gem 'turbo-sprockets-rails3', '0.2.9'
end

group :development do
  gem 'better_errors'
  gem "binding_of_caller"
  gem 'pry'
  gem 'byebug'
  gem 'rspec-rails'
  gem 'awesome_print'
  gem 'quiet_assets'
  gem 'copyright-header'
end

group :test do
  gem 'shoulda-matchers'
  gem 'shoulda'
  gem 'rspec-its'
  gem 'factory_girl_rails'
  gem 'factory_girl'
  gem 'faker'
end
