module OSB
  module CONFIG

    APP_CONFIG = HashWithIndifferentAccess.new(YAML.load_file(Rails.root.join('config','config.yml'))[Rails.env])
    APP_HOST ||= APP_CONFIG[:APP_HOST]
    APP_PROTOCOL ||= APP_CONFIG[:APP_PROTOCOL]

    ACTIVEMERCHANT_BILLING_MODE ||= APP_CONFIG[:ACTIVEMERCHANT_BILLING_MODE]

    PAYPAL ||= APP_CONFIG[:PAYPAL]
    PAYPAL_URL ||= PAYPAL[:PAYPAL_URL]
    PAYPAL_LOGIN ||= PAYPAL[:PAYPAL_LOGIN]
    PAYPAL_PASSWORD ||= PAYPAL[:PAYPAL_PASSWORD]
    PAYPAL_SIGNATURE ||= PAYPAL[:PAYPAL_SIGNATURE]
    PAYPAL_BUSINESS ||= PAYPAL[:PAYPAL_BUSINESS]

    WKHTMTTOPDF_PATH ||= APP_CONFIG[:WKHTMTTOPDF_PATH]

    SMTP_SETTING ||= APP_CONFIG[:SMTP_SETTING]

    ENCRYPTION_KEY ||= APP_CONFIG[:ENCRYPTION_KEY]

  end
end